-- Create todos table with exact specifications
CREATE TABLE IF NOT EXISTS todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task TEXT NOT NULL,
  status TEXT DEFAULT 'Not Started',
  user_id UUID REFERENCES auth.users,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for testing (no auth required)
CREATE POLICY "Enable all operations for todos" ON todos
  FOR ALL USING (true) WITH CHECK (true);

-- Insert 5 sample todos with different statuses
INSERT INTO todos (task, status, user_id) VALUES
  ('Set up Supabase database', 'Completed', NULL),
  ('Create Next.js frontend client', 'Completed', NULL),
  ('Test database connection', 'In Progress', NULL),
  ('Deploy to Vercel', 'Not Started', NULL),
  ('Add user authentication', 'Not Started', NULL)
ON CONFLICT DO NOTHING;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_todos_updated_at 
  BEFORE UPDATE ON todos 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();